Examples/SimpleBlogDemo/Controllers/EditController.cs
namespace SimpleBlogDemo.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    using Helpers;
    using Models;
    using System.IO;
    using System.Text;
    using Dropbox.Api.Files;
    using Dropbox.Api;
    using System;
    using System.Globalization;

    [Authorize, RequireHttpsOrXForwarded]
    public class EditController : AsyncController
    {
        private UsersStore store = new UsersStore();
        private UserProfile currentUser;

        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            this.currentUser = this.store.CurrentUser();

            base.Initialize(requestContext);
        }

        // GET: Edit/{id}
        public async Task<ActionResult> IndexAsync(string id)
        {
            using (var client = this.currentUser.GetAuthenticatedClient())
            {
                if (client == null)
                {
                    return RedirectToAction("Profile", "Home");
                }

                var articles = await client.GetArticleList();
                var filtered = from a in articles
                               where a.DisplayName == id
                               select a;
                var selected = filtered.FirstOrDefault();
                if (selected == null)
                {
                    return RedirectToAction("Display", "Blogs", new { blogname = this.currentUser.BlogName });
                }

                using (var download = await client.Files.DownloadAsync("/" + selected.Filename))
                {
                    var markdown = await download.GetContentAsStringAsync();

                    return View(Tuple.Create(markdown, selected));
                }
            }
        }

        // POST: /Edit
        [HttpPost, ValidateAntiForgeryToken, ValidateInput(enableValidation: false)]
        public async Task<ActionResult> IndexAsync(
            string filename,
            string content,
            string rev)
        {
            using (var client = this.currentUser.GetAuthenticatedClient())
            {
                if (client == null)
                {
                    return RedirectToAction("Profile", "Home");
                }

                using (var mem = new MemoryStream(Encoding.UTF8.GetBytes(content)))
                {
                    try
                    {
                        var updated = await client.Files.UploadAsync(
                            "/" + filename,
                            WriteMode.Overwrite.Instance,
                            body: mem);
                        rev = updated.Rev;
                    }
                    catch (ApiException<UploadError> e)
                    {
                        var uploadError = e.ErrorResponse;
                        if (uploadError.IsPath)
                        {
                            var reason = uploadError.AsPath.Value.Reason;
                            var id = filename.Split('.')[0];

                            var message = $"Unable to update {id}. Reason: {reason}";

                            this.Flash(message, FlashLevel.Warning);
                            return RedirectToAction("Index", new { id = id });
                        }
                    }
                }

                var metadata = ArticleMetadata.Parse(filename, rev);

                await client.GetArticle(this.currentUser.BlogName, metadata, bypassCache: true);

                this.Flash($"Updated '{metadata.Name}'.");
                return Redirect($"/Blogs/{this.currentUser.BlogName}/{metadata.DisplayName}");
            }
        }

        // GET: /Add
        public ActionResult Add()
        {
            return View();
        }

        // POST: /Add
        [HttpPost, ValidateAntiForgeryToken, ValidateInput(enableValidation: false)]
        public async Task<ActionResult> AddAsync(string name, DateTime date, string content)
        {
            var filename = string.Format(
                CultureInfo.InvariantCulture,
                "{0}.{1:yyyyMMdd}.md",
                name,
                date);

            using (var client = this.currentUser.GetAuthenticatedClient())
            {
                if (client == null)
                {
                    return RedirectToAction("Profile", "Home");
                }

                using (var mem = new MemoryStream(Encoding.UTF8.GetBytes(content)))
                {
                    var upload = await client.Files.UploadAsync("/" + filename, body: mem);

                    var metadata = ArticleMetadata.Parse(upload.Name, upload.Rev);

                    return Redirect(string.Format(
                        CultureInfo.InvariantCulture,
                        "/Blogs/{0}/{1}",
                        this.currentUser.BlogName,
                        metadata.DisplayName));
                }
            }
        }

        // POST: /Preview
        // This is called by an ajax request in preview.js
        [HttpPost, ValidateAntiForgeryToken, ValidateInput(enableValidation: false)]
        public ActionResult Preview(string markdown)
        {
            return Content(markdown.ParseMarkdown().ToString());
        }
    }
}

Examples/SimpleBlogDemo/Views/Edit/Add.cshtml
@{
    ViewBag.Title = "New Article";
}

<div class="row">
    <div class="col-md-offset-1 col-md-8">
        <h2>New Article</h2>

        @using (Html.BeginForm("Add", "Edit", FormMethod.Post, new { id = "add-form" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                <label class="control-label">Name</label>
                <input type="text" id="name" name="name" class="form-control" />
            </div>

            <div class="form-group">
                <label class="control-label">Date</label>
                <input type="date" id="date" name="date" class="form-control" placeholder="Effective date" />
            </div>

            <div class="form-group">
                <label class="control-label">Text</label>
                <textarea name="content" id="content" rows="20" class="form-control"></textarea>
            </div>

            <div class="text-right">
                <button id="preview" class="btn btn-default" disabled>Preview</button>
                <input type="submit" id="add" name="add" value="Add" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div class="modal fade" role="dialog" id="preview-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Preview</h4>
            </div>
            <div class="modal-body">
                <div id="preview-loading">
                    <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> loading...
                </div>
                <div id="preview-content" style="display: none;">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/preview.js" async></script>
    <script>
        $(document).ready(function () {
            $('#add-form').validate({
                rules: {
                    name: {
                        required: true,
                        minlength: 1
                    },
                    date: {
                        required: true,
                        date: true
                    },
                    content: {
                        required: true,
                        minlength: 10
                    }
                }
            });
        });
    </script> 
}


Examples/SimpleBlogDemo/Views/Edit/Index.cshtml
@model Tuple<string, ArticleMetadata>

@{
    var markdown = Model.Item1;
    var metadata = Model.Item2;
    
    ViewBag.Title = string.Format("Editing \"{0}\"", metadata.Name);
}

<h2>Editing &ldquo;@metadata.Name&rdquo;</h2>

@using (Html.BeginForm("Index", "Edit", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("filename", metadata.Filename)
    @Html.Hidden("rev", metadata.Rev)
    
    <div class="form-group">
        @Html.Label("Date", new { @class = "control-label" })
        <div class="form-control">
            @metadata.Date.ToShortDateString()
        </div>
    </div>
    
    <div class="form-group">
        @Html.Label("Content", new { @class = "control-label", @for = "content" })
        @Html.TextArea("content", markdown, new { @class = "form-control", rows=20 })
    </div>
    
    <div class="form-group text-right">
        <button id="preview" class="btn btn-default" disabled>Preview</button>
        <input type="submit" name="save" value="Save" class="btn btn-primary" />
    </div>
}

<div class="modal fade" role="dialog" id="preview-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Preview</h4>
            </div>
            <div class="modal-body">
                <div id="preview-loading">
                    <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> loading...
                </div>
                <div id="preview-content" style="display: none;">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/preview.js" async></script>
}